---
name: Checks

on: [push]

jobs:
  test-lints:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker-compose build  # Ensure the image is built with the correct tag
      - name: List Docker Images
        run: docker images  # Verify the image is built
      - name: Push Docker Image
        run: docker push steventr/recipe_api:1.0  # Push the image with the fixed tag
