---
name: Checks

on: [push]

jobs:
  test-lints:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Linting
        run: docker compose run --rm app sh -c "flake8"
      - name: Build Docker Image
        run: |
          docker build . -f Dockerfile -t steventr/recipe_api:1.0  # Adjust Dockerfile path if necessary
      - name: List Docker Images
        run: docker images  # Verify the image is built
      - name: Push Docker Image
        run: docker push steventr/recipe_api:1.0  # Push the image with the fixed tag
